// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxcqcnjbjgpexjdejeqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Y3FjbmpiamdwZXhqZGVqZXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjI3NTgsImV4cCI6MjA2MDI5ODc1OH0.dBi_AcBXSnXSXwMpgjXGHfsiefcukAZ1nYqcbmXpypc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);